### ISSUE TITLE
Product Images

### ISSUE THREAD

**Issue by verygoodsoftwarenotvirus** [dairycart/dairycart#40]
Everybody likes pictures.

**Comment by verygoodsoftwarenotvirus** [comment]
How product images will work:

images associated with products can be raw images, or urls hosted elsewhere
- if they are hosted elsewhere:
    - the server will download an image at a time
- resize it to no larger than 100x100 and save
- resize it to no larger than 500x500 and save
- save the original image
- save all three urls (plus the source URL if the image was hosted elsewhere) in the database

**Comment by luqmaan** [comment]
🐒
